ECHR and RS db setup routines merge.
maastrichtlawtech/case-law-explorer pull request #26
Opened 2023-09-25 12:55 UTC by Cloud956

Merging latest (hopefully final) changes to the backend.

2023-09-26 06:28 UTC, shashankmc commented on .env
Can you provide a comment on the purpose of those starting dates please? How is this different from providing it in Airflow?

2023-09-26 06:31 UTC, shashankmc requested changes
Can we move towards utilizing proper logging methods rather than print statements please? Or would you rather fix that in a separate issue/branch?

2023-09-26 14:58 UTC, Cloud956 commented on .env
I included comments for these variables in .env in the newest update.

2023-09-27 10:20 UTC, shashankmc approved these changes
Great, thanks for the changes!

2023-09-27 10:21 UTC, merged